version: "3"
services:
    mysql:
        image: "mysql:8.0.30"
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "admin"
            MYSQL_USER: "test"
            MYSQL_PASSWORD: "test"
            MYSQL_DATABASE: "test"
        volumes:
            - my-datavolume:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin
        restart: always
        depends_on:
            - mysql
        ports:
            - 8080:80
        environment:
            PMA_HOST: mysql
volumes:
    my-datavolume:
